### ISSUE TITLE
Feature Request: indent level dependent bullet character

### ISSUE THREAD

**Issue by notuntoward** [lilian-pouliquen/obsidian-custom-list-character#2]
I like how emacs displays multi-level bullets (below).  I don't know if this is feasible for Obsidian, but I'd love it if this plugin could also make it possible to have a different character for each bullet indentation level.

<img width="442" alt="image" src="https://github.com/lilian-pouliquen/obsidian-custom-list-character/assets/3851891/d0a7140e-c380-43a8-ab3c-7254bf027c1f">

**Comment by lilian-pouliquen** [comment]
Hello!
Thanks for your interest in my plugin!

I did some research to see if I can include these changes in the plugin and if it is following its main idea.
Unfortunately, it seems that I cannot add your feature in the plugin. Actually, what you want seems to be a CSS snippet for your Obsidian editor!

Here are some links I found that should help you (I didn't find a snippet for emacs stiyling):
* https://help.obsidian.md/Extending+Obsidian/CSS+snippets
* https://github.com/mgmeyers/obsidian-style-settings#obsidian-style-settings-plugin
* https://github.com/Dmytro-Shulha/obsidian-css-snippets/blob/master/Snippets/Lists%20-%20(un)ordered.md
* https://forum.obsidian.md/t/help-changing-list-style-type-in-editor/34009

(I am trying to make the snippet you want)

**Comment by lilian-pouliquen** [comment]
@notuntoward
After a bit of work and research, I wrote a CSS snippet that displays unordered lists according to your screenshot. It's working only in live preview, I couldn't find a way to make it work on reading mode due to the fact I cannot identify the level of each item.

The snippet covers only the 5 first levels, as it is shown on your screenshot. Feel free to add other levels with other shapes and edit bullet sizes if you need it.

To use the snippet, Just download and unzip the CSS file attached to this message and place it under your_vault/snippets/, open Obsidian and go to `Settings > Appearance > CSS Snippets` and  enable `emacs_unordered_list`

I hope it will be useful to you,
Thanks again for your proposition.

[emacs_unordered_list.zip](https://github.com/lilian-pouliquen/obsidian-custom-list-character/files/13537480/emacs_unordered_list.zip)

**Comment by notuntoward** [comment]
Thanks!  I like it, and am going to use it even if it doesn't go all the way to reading mode.

I bet other people would be interested in this too.  If you wanted, you could share it on reddit, [here](https://www.reddit.com/r/ObsidianMD/comments/urhx0g/lets_gather_all_the_best_css_snippets/).

**Comment by lilian-pouliquen** [comment]
Hello @notuntoward!
I'm glad you like it, I made a gist [here](https://gist.github.com/lilian-pouliquen/358fd4ecaff739755fcd3db4c5bec5b0) for people interested. I don't have a reddit account, feel free to post the link of the gist in the subreddit you gave me

Have a great day!
